//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace One {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("One.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duck object is Killed, you can also kill your Objects if any .....
        /// </summary>
        internal static string StrCleaningMSG {
            get {
                return ResourceManager.GetString("StrCleaningMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fly Behavior not set !!!.
        /// </summary>
        internal static string StrExPerformFly {
            get {
                return ResourceManager.GetString("StrExPerformFly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quack Behavior not set !!!!.
        /// </summary>
        internal static string StrExPerformQuack {
            get {
                return ResourceManager.GetString("StrExPerformQuack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---- I am a real Mallard Duck -----.
        /// </summary>
        internal static string StrMallardDisplay {
            get {
                return ResourceManager.GetString("StrMallardDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Silence ------.
        /// </summary>
        internal static string StrMuteQuack {
            get {
                return ResourceManager.GetString("StrMuteQuack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------ I Can&apos;t Fly :-( ------.
        /// </summary>
        internal static string StrNoFly {
            get {
                return ResourceManager.GetString("StrNoFly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---- I am Flying :-) -----.
        /// </summary>
        internal static string StrNormalFly {
            get {
                return ResourceManager.GetString("StrNormalFly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Quack Quack ------.
        /// </summary>
        internal static string StrNormalQuack {
            get {
                return ResourceManager.GetString("StrNormalQuack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------ I am Flying with Rocket :-D --------.
        /// </summary>
        internal static string StrRocketFly {
            get {
                return ResourceManager.GetString("StrRocketFly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change of behavior @ Runtime !!!!.
        /// </summary>
        internal static string StrRTCB {
            get {
                return ResourceManager.GetString("StrRTCB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ----- Squeak Squeak -----.
        /// </summary>
        internal static string StrSqueak {
            get {
                return ResourceManager.GetString("StrSqueak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Ducks can Swim so am i !!!!.
        /// </summary>
        internal static string StrSwim {
            get {
                return ResourceManager.GetString("StrSwim", resourceCulture);
            }
        }
    }
}
